# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('one_name', models.CharField(max_length=3)),
                ('one_balance', models.FloatField()),
                ('two_name', models.CharField(max_length=3)),
                ('two_balance', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='EthBtc',
        ),
    ]
